services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

###> doctrine/doctrine-bundle ###
    mysql:
        image: mysql:8.0
        ports:
            - "33061:3306"
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        volumes:
            - ./storage/tmp/db:/var/lib/mysql/
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
