### Calculate Price
POST http://127.0.0.1:8000/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D100"
}

### Calculate Price with existed and wrong coupon
POST http://127.0.0.1:8000/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "D15"
}

### Calculate Price without coupon
POST http://127.0.0.1:8000/calculate-price
Accept: application/json
Content-Type: application/json

{
"product": 1,
"taxNumber": "DE123456789"
}

### Calculate Price without fields
POST http://127.0.0.1:8000/calculate-price
Accept: application/json
Content-Type: application/json

{
}

### Execute Purchase with paypal success
POST http://127.0.0.1:8000/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 2,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}

### Execute Purchase with paypal error
POST http://127.0.0.1:8000/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal"
}

### Execute Purchase with stripe error
POST http://127.0.0.1:8000/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 3,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "stripe"
}

### Execute Purchase with stripe success
POST http://127.0.0.1:8000/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "IT12345678900",
  "paymentProcessor": "stripe"
}

### Execute Purchase with wrong paymentProcessor
POST http://127.0.0.1:8000/purchase
Accept: application/json
Content-Type: application/json

{
  "product": 2,
  "taxNumber": "IT12345678900",
  "couponCode": "D15",
  "paymentProcessor": "paypal2"
}

### Execute Purchase without fields
POST http://127.0.0.1:8000/purchase
Accept: application/json
Content-Type: application/json

{
}
